name: Build and Release JAR (Java 17 - Corretto)

on:
  push:
    branches:
      - main

jobs:
  build-release:
    if: startsWith(github.event.head_commit.message, 'alpha:') ||
        startsWith(github.event.head_commit.message, 'beta:')  ||
        startsWith(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push tags and create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version, channel, and commit hash
        id: meta
        run: |
          msg="${{ github.event.head_commit.message }}"
          channel="${msg%%:*}"                 # alpha / beta / release
          version="$(echo ${msg##*:} | xargs)" # strip leading space
          commit="$(git rev-parse --short HEAD)"
          echo "CHANNEL=$channel" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "COMMIT=$commit" >> $GITHUB_ENV
          echo "FULL_TAG=${CHANNEL^}-${VERSION}" >> $GITHUB_ENV # Alpha-2.0.0
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV           # 2.0.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK (Corretto 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build JAR with version and commit hash
        run: ./gradlew clean build --no-daemon -Pversion=${{ env.VERSION }}

      - name: Rename built JAR to include commit hash
        run: |
          mkdir -p artifacts
          # assuming your JAR name starts with Hephaestus-${VERSION}
          srcJar=$(ls build/libs/Hephaestus-${{ env.VERSION }}*.jar | head -n 1)
          destJar="artifacts/Hephaestus-${{ env.VERSION }}-${{ env.COMMIT }}.jar"
          mv "$srcJar" "$destJar"
          echo "JAR_PATH=$destJar" >> $GITHUB_ENV

      - name: Push tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ env.FULL_TAG }}" -f
          git tag "${{ env.VERSION_TAG }}" -f
          git push origin "${{ env.FULL_TAG }}" --force
          git push origin "${{ env.VERSION_TAG }}" --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FULL_TAG }}
          name: "Hephaestus ${{ env.FULL_TAG }}"
          draft: false
          prerelease: ${{ env.CHANNEL != 'release' }}
          files: ${{ env.JAR_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
