name: Build and Release JAR (Java 8 - Corretto)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK (Corretto 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'gradle'

      - name: Build JAR
        run: ./gradlew build --no-daemon

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hephaestus-JAR
          path: build/libs/Hephaestus-2.0.0.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR from artifact
        uses: actions/download-artifact@v4
        with:
          name: Hephaestus-JAR
          path: artifacts/

      - name: Get short commit SHA
        run: echo "TAG_NAME=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Hephaestus ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
          files: artifacts/Hephaestus-1.0.0-SNAPSHOT-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
